### Numpy 

###### 1. Import numpy as np and print the version number.

In [19]:
# To check the version of numpy package
import numpy as np
np.__version__

'1.16.2'

###### 2. Create a 1D array of numbers from 0 to 9

In [21]:
a = np.arange(0,9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

###### 3. Create a 3×3 numpy array of all True’s(1's)

In [30]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

###### 4. Convert a 1D array to a 2D array with 2 rows

In [38]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

###### 5. Write a NumPy program to generate six random integers between 10 and 30

In [39]:
a = np.random.randint(10,30,6)
a

array([20, 16, 25, 10, 27, 13])

###### 6. Write a NumPy program to create a 3x3x3 array with random values

In [41]:
a = np.random.randint(1,10,27).reshape(3,3,3)
a

array([[[8, 4, 3],
        [6, 1, 8],
        [1, 1, 9]],

       [[7, 1, 4],
        [2, 5, 8],
        [8, 2, 6]],

       [[9, 5, 5],
        [2, 6, 1],
        [6, 8, 1]]])

###### 7.Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [48]:
a = np.random.randint(1,50,25).reshape(5,5)
print(a)
print(a.max())
print(a.min())

[[35 14 14 18  3]
 [14 34 40 29 36]
 [ 5 48  9 38  3]
 [ 5 25 25  3 24]
 [ 5 41 35 21 34]]
48
3


###### 8 Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable

In [59]:
a = np.random.randint(1,50,40).reshape(10,4)
print(a)
a[0:5]

[[33 42 36 26]
 [26 16 14 16]
 [12 28  3 26]
 [38 13 12  5]
 [40  4 47 43]
 [28 27 34 11]
 [40 40 25 16]
 [21  8  1 49]
 [14 21  2 38]
 [25 19  7  7]]


array([[33, 42, 36, 26],
       [26, 16, 14, 16],
       [12, 28,  3, 26],
       [38, 13, 12,  5],
       [40,  4, 47, 43]])

###### 9.How to reverse the rows of a 2D array?

###### arr = np.arange(9).reshape(3,3)

a = [[1,2,3],[2,3,4],[3,4,5]]

out = [[3,4,5],[2,3,4],[1,2,3]]

In [62]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

###### 10. Create 1D array with random numbers and replace all odd numbers in arr with -1

In [68]:
a = np.random.randint(1,20,20)
print(a)
for i in range(len(a)):
    if a[i]%2!=0:
        a[i]=-1
print(a)

[ 9 13 10  7 16 18  6  1 14  4  6 19 12  5  1  9  6 18  2 10]
[-1 -1 10 -1 16 18  6 -1 14  4  6 -1 12 -1 -1 -1  6 18  2 10]
